spring.application.name=chatapp

# MongoDB Configuration
#spring.data.mongo.uri=mongodb://localhost:27017/chatapp
spring.data.mongodb.uri=mongodb://localhost:27017/chatapp
spring.data.mongodb.database=chatapp

# Optional MongoDB Connection Pool Settings (adjust as needed)
spring.data.mongodb.auto-index-creation=true

# Logging (Optional)
logging.level.org.springframework.data.mongodb=INFO

# Optional: Connection Pool Settings
spring.data.mongodb.connection-timeout=10000
spring.data.mongodb.max-connections-per-host=100